### ISSUE TITLE
Suggestion: A way to input F13-F24 keys.

### ISSUE THREAD

**Issue by SomeGuyNamedJJ** [StreamController/OSPlugin#14]
When I used Windows, using the F13-F24 keys were extremely useful through my Stream Deck to use in apps that do not allow you to use combinations for actions. If there was a button in the Hotkey Recorder menu that allowed you to input uncommon keys, such as these F13-F24 keys, it would make setting up the Stream Deck for these apps much easier.

**Comment by SomeGuyNamedJJ** [comment]
Oops, didn't even realize this was an existing issue, I definitely remember checking for that.

**Comment by Core447** [comment]
No problem
