### ISSUE TITLE
Run command every x seconds continues when not displaying page

### ISSUE THREAD

**Issue by jfbauer432** [StreamController/OSPlugin#17]
If you have an action on a page in StreamController that runs a command every x seconds.  It will continue to do so even when no longer displaying that page.  But you have to have to display that page initially for this to happen.

To reproduce:
- Create a some page (don't use initial/default one) add a command that runs every x seconds.  10 seconds will be good.
- Have the command do something (e.g. append a message to a file) so you can tell when it runs
- (re)Run StreamController
- Wait at least 10 seconds (or whatever time you specified) and verify command is not being run.
- Switch to page with the run-every-x-seconds action.
- Verify the command is being run as expected.
- Switch back to original page and see that the command is still running.

Version info:
- Running from my own build at commit d286e822  OR
- Running from official flatpak version 1.5.0-beta.6
- OS: Linux Mint 22
- Stream Decks: 1 mini

**Comment by Core447** [comment]
This is now fixed and a4075c59a120d07402ecd83a3fe7e9ada152febc adds a new option to enable the old behavior if wanted.
