### ISSUE TITLE
CPU Temperature not working - ThinkPad P14s Gen 3

### ISSUE THREAD

**Issue by rombert** [StreamController/OSPlugin#18]
The CPU temperature shows N/A for my laptop. Maybe the plugin is looking at the wrong data Here's what the sensors command outputs for me

```
$ sensors
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +96.2°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +96.0°C  

amdgpu-pci-0400
Adapter: PCI adapter
vddgfx:        1.36 V  
vddnb:       729.00 mV 
edge:         +73.0°C  
PPT:          49.08 W  
sclk:         200 MHz 

BAT0-acpi-0
Adapter: ACPI interface
in0:          13.17 V  
power1:        4.13 W  

ath11k_hwmon-pci-0200
Adapter: PCI adapter
temp1:        +58.0°C  

thinkpad-isa-0000
Adapter: ISA adapter
fan1:        3990 RPM
CPU:          +96.0°C  
GPU:              N/A  
temp3:        +96.0°C  
temp4:         +0.0°C  
temp5:        +96.0°C  
temp6:        +96.0°C  
temp7:        +96.0°C  
temp8:            N/A  
pwm1:            128%

nvme-pci-0300
Adapter: PCI adapter
Composite:    +38.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +38.9°C  (low  = -273.1°C, high = +65261.8°C)
```

**Comment by Core447** [comment]
Yes, atm the plugin only looks at `coretemp`

**Comment by rombert** [comment]
Would you consider extending the plugin to look for other data as well? I would be happy to test and/or provide test data.

**Comment by Core447** [comment]
Sure, but I first have to research what keys can be used.

**Comment by justinthegeek** [comment]
Looks like we should be able to pull quite a bit of info. Give me some time and I'll see what I can do. :D

`>>> import psutil
>>> psutil.sensors_temperatures()
{'acpitz': [shwtemp(label='', current=27.8, high=None, critical=None)], 'nvme': [shwtemp(label='Composite', current=22.85, high=81.85, critical=84.85), shwtemp(label='Sensor 1', current=22.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=29.85, high=65261.85, critical=65261.85), shwtemp(label='Composite', current=30.85, high=81.85, critical=84.85), shwtemp(label='Sensor 1', current=30.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=38.85, high=65261.85, critical=65261.85), shwtemp(label='Composite', current=32.85, high=81.85, critical=84.85), shwtemp(label='Sensor 1', current=32.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=33.85, high=65261.85, critical=65261.85), shwtemp(label='Composite', current=30.85, high=81.85, critical=84.85), shwtemp(label='Sensor 1', current=30.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=31.85, high=65261.85, critical=65261.85)], 'nct6687': [shwtemp(label='PECI 0.0', current=20.5, high=0.0, critical=0.0), shwtemp(label='Diode 0 (curr)', current=29.0, high=0.0, critical=0.0), shwtemp(label='Thermistor 15', current=20.0, high=122.0, critical=122.0), shwtemp(label='PCH CHIP', current=52.0, high=0.0, critical=0.0), shwtemp(label='Thermistor 16', current=20.0, high=0.0, critical=0.0), shwtemp(label='Thermistor 0', current=16.0, high=0.0, critical=0.0), shwtemp(label='Thermistor 1', current=31.0, high=0.0, critical=0.0)], 'spd5118': [shwtemp(label='', current=20.75, high=55.0, critical=85.0), shwtemp(label='', current=21.5, high=55.0, critical=85.0), shwtemp(label='', current=21.75, high=55.0, critical=85.0), shwtemp(label='', current=21.25, high=55.0, critical=85.0)], 'coretemp': [shwtemp(label='Package id 0', current=21.0, high=80.0, critical=100.0), shwtemp(label='Core 8', current=18.0, high=80.0, critical=100.0), shwtemp(label='Core 12', current=20.0, high=80.0, critical=100.0), shwtemp(label='Core 16', current=16.0, high=80.0, critical=100.0), shwtemp(label='Core 0', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 20', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 24', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 28', current=18.0, high=80.0, critical=100.0), shwtemp(label='Core 32', current=18.0, high=80.0, critical=100.0), shwtemp(label='Core 33', current=18.0, high=80.0, critical=100.0), shwtemp(label='Core 34', current=18.0, high=80.0, critical=100.0), shwtemp(label='Core 35', current=18.0, high=80.0, critical=100.0), shwtemp(label='Core 36', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 37', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 38', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 39', current=19.0, high=80.0, critical=100.0), shwtemp(label='Core 4', current=17.0, high=80.0, critical=100.0)]}
>>>`

**Comment by rombert** [comment]
Awesome, thanks!

**Comment by rombert** [comment]
I see this was closed as fixed (thanks @zelims for the contribution!) but the plugin store update was backed out with https://github.com/StreamController/StreamController-Store/commit/26b71ac3b14865fef15498875f7a3c6c03a3e04a . I am not sure what the problem is, but if I can help somehow ( testing?) please let me know. Thanks!

**Comment by Core447** [comment]
> . I am not sure what the problem is, but if I can help somehow ( testing?) please let me know. Thanks!

After the update some users reported weird behaviors, which might be unrelated, but that's why I pulled that update again. Hope I'm gonna be able to publish it again soon - Sorry for the inconvenience

**Comment by Core447** [comment]
Update: It happened again - The updated plugin doesn't load....

**Comment by rombert** [comment]
@Core447 - can I test it locally? I only have AMD CPUs though, not sure what it affects.

**Comment by Core447** [comment]
> @Core447 - can I test it locally? I only have AMD CPUs though, not sure what it affects.

Yeah, you can add the plugin as a custom plugin in the settings under store (https://github.com/StreamController/OSPlugin/). You should then have to "OSPlugin"s in the store, one of them should have an update button, click it to install it. To ensure that the app won't downgrade automatically on the next start, disable auto store updates in the settings. 

I just did the same, and I didn't have any problems... Very weird...
