### ISSUE TITLE
Error: Gtk-CRITICAL ** whe typing command

### ISSUE THREAD

**Issue by 4s3ti** [StreamController/OSPlugin#2]
This seems to be rather minor issue, but noticed the following error when writing the command in the "run command" option. 

Steps to reproduce: 
* Start streamcontroller from the terminal (to make it easier to observe the error)
* Add OS Run Command action to a button
* Write in the "command" text box

![2024-04-12 21-47-07](https://github.com/StreamController/OSPlugin/assets/14358086/b5816183-dd41-444a-b0d0-bf2c0ee59caf)

**Comment by Core447** [comment]
This seams to happen with all Adw.EntryRows and is a known problem [(here)](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/824) and there's nothing I can really do about it.
