### ISSUE TITLE
bug: New write text feature seems not to be working

### ISSUE THREAD

**Issue by 4s3ti** [StreamController/OSPlugin#3]
Happens both on flatpak and python venv, action shows error icon and does nothing. No logs are printed. 

**Steps to reproduce:**

* Add action
* press button

https://github.com/StreamController/OSPlugin/assets/14358086/cc538e29-75e6-4931-bb78-a840da91d2b6

**System Information:**
```
❯neofetch
                   -`
                  .o+`
                 `ooo/
                `+oooo:
               `+oooooo:
               -+oooooo+:
             `/:-:++oooo+:
            `/++++/+++++++:              f0rs3ti@nebu
           `/++++++++++++++:             ------------
          `/+++ooooooooooooo/`           OS: Arch Linux x86_64
         ./ooosssso++osssssso+`          Host: XPS 15 9530
        .oossssso-````/ossssss+`         Kernel: 6.8.5-zen1-1-zen
       -osssssso.      :ssssssso.        Uptime: 6 hours, 49 mins
      :osssssss/        osssso+++.       Packages: 984 (pacman), 19 (flatpak)
     /ossssssss/        +ssssooo/-       Shell: zsh 5.9
   `/ossssso+/:-        -:/+osssso+-     Resolution: 5120x1440
  `+sso+:-`                 `.-/+oso:    WM: sway
 `++:.                           `-/+/   Terminal: tmux
 .`                                 `/   CPU: 13th Gen Intel i7-13700H (20) @ 4.800GHz
                                         GPU: Intel Raptor Lake-P [Iris Xe Graphics]
                                         Memory: 11062MiB / 63973MiB



```

**Comment by Core447** [comment]
![image](https://github.com/StreamController/OSPlugin/assets/100139110/40f52c9d-9983-479f-b9e4-00052fe9458e)
You're getting: `/dev/uinput cannot be opened for writing`. This means the Hotkey action isn't working for you either, is it? Did you change something in the Flatpak permissions?

**Comment by 4s3ti** [comment]
Nope I did not change anything. just the standard flatpak installation and as for the python venv nothing as well, just like the docs

**Comment by Core447** [comment]
Can you check if you're in the `input` group?

**Comment by Core447** [comment]
Could you please check if any groups beside root are listed in the output of this command: `ls -al /dev/uinput`?

**Comment by Core447** [comment]
For anyone else having the same problem, please read [this](https://github.com/StreamController/OSPlugin?tab=readme-ov-file#hotkeys--write-text) on how to fix this
